### ISSUE TITLE
When tried to create a post without filling all fields it redirects me to 404 page not found.

### ISSUE THREAD

**Issue by coolwidgets** [ikkez/fabulog#4] opened 2015-01-16 18:50 UTC
Why there are no validation rules when creating/editing posts? When I tried to create a post without filling all mandatory fields it redirect me to 404 page not found. Instead of showing 404 you should show user some error message and show filled fields (what user filled in textbox). Its very annoying for a user.

**Comment by ikkez** [comment] 2015-01-16 19:18
Hi. thanks for noticing me. Well that is a duplicate of #2. I have not focused on those validation things and other parts yet. I wrote fabulog as a playground for me to build and improve the Cortex mapper. Hence there might be things that make the user experience pretty annoying, yes - sorry for this. But I will improve that when i find the time to push fabulog on the next level.

**Comment by ikkez** [comment] 2015-03-08 18:33
fixed

**Closed by ikkez** 2015-03-08 18:33 UTC
Labels: bug, duplicate
